name: Justanis
favicon: null
layout_spectrum: 0.766933391103521
typography_spectrum: 0.7321737864986062
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.10042579309083521
  lightness: 0.739616121398285
  saturation: 0.17364839324727654
  rhythmicContrast: 0.02317981654778123
purpose: []
