name: Justanis
favicon: null
layout_spectrum: 1
typography_spectrum: 0.08097
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1632ff'
    - '#de0008'
    - '#fcc000'
    - '#ffffff'
    - '#919fff'
  brandStrength: 0.5
  lightness: 0.739616121398285
  saturation: 0.17364839324727654
  rhythmicContrast: 0.02317981654778123
purpose: []
